=== just4satyam/repo31mar/src/main/resources/api/schemas/put-autoscalingpolicy.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "description": "CloudHub Auto Scaling Policy",
  "allowAdditionalProperties": false,
  "properties": {
    "id": {
      "type": "string",
      "description": "The auto scaling policy ID"
    },
    "enabled": {
      "type": "boolean",
      "description": "Whether the policy is enabled"
    },
    "description": {
      "type": "string",
      "minLength": 1,
      "description": "The auto scaling policy name"
    },
    "scaleType": {
      "type": "string",
      "enum": ["WORKER_COUNT", "WORKER_SIZE"],
      "description": "The scale type of the auto scaling policy"
    },
    "metric": {
      "type": "string",
      "enum": ["CPU", "MEMORY"],
      "description": "The metric based on which auto scaling policy scales"
    },
    "maxScale": {
      "type": "number",
      "enum": [0.1, 0.2, 1, 2, 3, 4, 5, 6, 7, 8, 16],
      "description": "The maximum number of workers or size of workers for auto scaling"
    },
    "minScale": {
      "type": "number",
      "enum": [0.1, 0.2, 1, 2, 3, 4, 5, 6, 7, 8, 16],
      "description": "The minimum number of workers or size of workers for auto scaling"
    },
    "scaleUpNextScaleWaitMins": {
      "type": "number",
      "description": "Number of minutes to wait before applying new scale up policy"
    },
    "scaleDownNextScaleWaitMins": {
      "type": "number",
      "description": "Number of minutes to wait before applying new scale down policy"
    },
    "scaleUp": {
      "type": "object",
      "description": "Scale up policy",
      "properties": {
        "value": {
          "type": "number",
          "description": "The CPU or memory usage above which scale up policy will take effect"
        },
        "periodCount": {
          "type": "number",
          "description": "The time in minutes to monitor the CPU/memory for high usage before scaling up"
        }
      }
    },
    "scaleDown": {
      "type": "object",
      "description": "Scale down policy",
      "properties": {
        "value": {
          "type": "number",
          "description": "The CPU or memory usage below which scale down policy will take effect"
        },
        "periodCount": {
          "type": "number",
          "description": "The time in minutes to monitor the CPU/memory for low usage before scaling down"
        }
      }
    }
  }
}

=== just4satyam/repo31mar/src/main/resources/api/examples/auto-scaling-policy.json
{
    "id": "5994bb6ee4b0fce59b281798",
    "enabled": true,
    "maxScale": 2,
    "minScale": 1,
    "scaleType": "WORKER_COUNT",
    "description": "policy_name",
    "metric": "CPU",
    "scaleUpNextScaleWaitMins": 30,
    "scaleDownNextScaleWaitMins": 30,
    "scaleUp": {
        "value": 80,
        "periodMins": 1,
        "periodCount": 10
    },
    "scaleDown": {
        "value": 20,
        "periodMins": 1,
        "periodCount": 10
    }
}

=== just4satyam/repo31mar/src/main/resources/api/examples/post-auto-scaling-policy.json
{
    "maxScale": 2,
    "minScale": 1,
    "scaleType": "WORKER_COUNT",
    "description": "policy_name",
    "metric": "CPU",
    "scaleUpNextScaleWaitMins": 30,
    "scaleDownNextScaleWaitMins": 30,
    "scaleUp": {
        "value": 80,
        "periodCount": 10
    },
    "scaleDown": {
        "value": 20,
        "periodCount": 10
    }
}
